### ISSUE TITLE
add auto-decryption of messages

### ISSUE THREAD

**Issue by mwfarb** [SafeSlingerProject/SafeSlinger-iOS#4]
Version 1.7.0. Messages are not currently automatically decrypted when users are logged in. Provide a an auto-decrypt setting users can configure which defaults to true. When the passphrase is cached, messages should decrypt without having to press "tap to decrypt". Similarly, the moment a user successfully logs in, a background job should seek out encrypted messages and attempt to automatically decrypt them.

**Comment by brnunes** [comment]
I finished the auto decryption and everything seems to be working fine. I tested with multiple accounts on the same device, checking and unchecking the auto-decryption, and everything worked as expected.
I had to add a new column to the `msgtable` to indicate if a message has been already read or not, since now we can't differentiate them just by being encrypted/decrypted. The patch will be executed if the user is running the version 1.8.1 or prior, but will not be executed if the version is already the 1.8.2 (not yet released). In order to test, you will have to reinstall the app, or change the logic [here](https://github.com/SafeSlingerProject/SafeSlinger-iOS/blob/3b9ba83d8f9a46817d6c43e1592386bee549fd64/safeslingermessager/safeslingermessager/SafeSlingerDB.m#L138-L154), and call the `patchForUnreadMessagesFlag` method.

A few notes on some problems that are not directly related to this task but I noticed while working on it:

- If the user created more than one public/private key pair, he will receive all the messages when logged in with any key pair. If the message was sent to a key that is not the currently logged in, the messages will show up but he won't be able to decrypt. I think we have already talked about this issue. It happens because the only destination identification is the push token, which is the same for accounts created on the same device.
A possible solution for this, when auto-decryption is enabled, is to just not show any messages that we could not decrypt when the user logged in or when the message arrived. That's an indicator that the message was addressed to another key pair.

- When the nonce for a new message is received, it is first inserted in the `ciphertable` with the `keyid` "UNDEFINED". Then the encrypted message is downloaded from the server and the `ciphertable` is updated with the correct `keyid` and `ciphertext`. If for some reason the download of the encrypted message fails, the message will stay in the `ciphertable` with the `keyid` "UNKNOWN" and will be shown as "Message expired". We never try to download that message again.
Also, if multiple messages arrive in a short period of time and the user is in the screen where the list of conversation threads is shown, we might reload the threads while one message is temporarily stored in the `ciphertable` with `keyid` "UNKNOWN". That will appear as a conversation with an unknown contact. Then, when that message is downloaded and decrypted, we will again reload the threads and the conversation will disappear because that message has been downloaded, decrypted and is now in the `msgtable`.
One solution for this problem would be to store the nonces in a different table. We could also just not show messages that have keyid "UNKNOWN" since the user won't be able to decrypt them anyway. Regardless, we should always check if we have nonces for messages that were still not downloaded, and try to download them.

**Comment by mwfarb** [comment]
@brnunes Thanks so much for your work on this! Unfortunately we may have to keep the unknown messages for both cases in the database for now even though they cannot be read. The issue is iOS does not allow us to separate incoming pushes from what the user sees. The push message, to be secret cannot reveal the senders information until decryption, and when push messages arrive, we cannot analyze any of the message contents to determine if we want to show the push message or not, even the message id before the user sees the alert. So that leaves the issue of, why not just delete unusable messages when the user opens the app? Well, now we have a case where the user sees a push message alert and when they open the app, poof! no message. This seems like a bug to the user similar to issue #76. So, for now, we want to have the database reflect any incoming message, even unusable ones, so the push alerts will correspond to database data. We may get support questions in either case, but at least our users can be assured delivery has occurred.
