### ISSUE TITLE
crash on contact selection

### ISSUE THREAD

**Issue by mwfarb** [SafeSlingerProject/SafeSlinger-iOS#67]
Tested on 1.8.1 with iOS 6 and 8:
- Select Compose tab, Select Recipients button.
- Press the info "i" button on any Recipient.
- Expected Menu loads with "Use Another" and other options.
- Press Cancel
- Press hardware Home key.
- Go to Settings App, change SafeSlinger Contacts permission to disabled.
- Press hardware Home key.
- Navigate back to SafeSlinger.
- Select Compose tab, Select Recipients button.
- Press the info "i" button on any Recipient.
- Crash.

**Comment by brnunes** [comment]
Now when we have no permission to access the contacts, we show only the options available.

I was wondering if we should show an alert telling the user that there will be more options if we are granted permission to access the contacts, but if we show that alert every time it might become annoying.
I also left the option "Create New" because it opens a screen saying that "This app does not have access to your contacts. You can enable access in Privacy Settings".

**Comment by mwfarb** [comment]
I think if we also leave in Use Another, then that should be sufficient. You're right, we shouldn't keep annoying users with that warning message every time they open the menu. When contacts options are denied, we can't search for them, but if we allow them to click Use Another to search for contacts to use they will at least see the same "This app does not have access to your contacts. You can enable access in Privacy Settings"

**Comment by mwfarb** [comment]
Closed by @brnunes with 69c7ff5.
